# Site settings
title: Valantis Kamayiannis
email: kamayiannis@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Software engineer, web enthusiast, drummer and proud father of one. 
  I will try to give ideas, tips, thoughts, anything that might matter to anyone.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: vkamayiannis
github_username:  vkamayiannis

# Build settings
markdown: kramdown
pages_list:       
  About: '/about'
  Archive: '/archives'
  Feed: '/feed.xml'