# Site settings
title: Valantis Kamayiannis
owner: Valantis Kamayiannis
email: kamayiannis@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Software engineer, web enthusiast, drummer and proud father of one. 
  I will try to give ideas, tips, thoughts, anything that might matter to anyone.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vkamayiannis.github.io/" # the base hostname & protocol for your site
twitter_username: vkamayiannis
github_username:  vkamayiannis
gravatar_id: 295444c667fe78caffe72b403348e1a7
linkedin_username: valantis-kamayiannis
linkedin_name: Valantis Kamayiannis
paginate: 2
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
pages_list:       
  About: '/about'
  Archive: '/archives'
  Contact: '/contact'
  Feed: '/feed.xml'